spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://tn8673436_db_user:1KwLrSxJBWraoqg7@cluster202.rmrmh3w.mongodb.net/mylapdb?retryWrites=true&w=majority&appName=Cluster202

server.port=8080